<?php

namespace AppBundle\Repository;

/**
 * OpeningHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHourRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderedHoursbyRestaurant($restaurant){
        $query = $this->createQueryBuilder('hours')
            ->select('hours')
            ->where('hours.restaurant = :restaurant')
            ->orderBy('hours.weekday')
            ->setParameter('restaurant', $restaurant)
            ->getQuery();
        return $query->getResult();
    }
}
