<?php

namespace AppBundle\Repository;

/**
 * WeekdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekdayRepository extends \Doctrine\ORM\EntityRepository
{
}
